source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'UrbanAirship-GA-Ext_Example', :exclusive => true do
  pod 'UrbanAirship-GA-Ext', :path => '../'
end

target 'UrbanAirship-GA-Ext_Tests', :exclusive => true do
  pod 'UrbanAirship-GA-Ext', :path => '../'

  
end
