source 'https://github.com/CocoaPods/Specs.git'

target 'UrbanAirship-iOS-GA-Tracker_Example', :exclusive => true do
  pod 'UrbanAirship-iOS-GA-Tracker', :path => ".."
end

target 'UrbanAirship-iOS-GA-Tracker_Tests', :exclusive => true do
  pod 'UrbanAirship-iOS-GA-Tracker', :path => ".."
  
end
